// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VCare.Modules.CarePlans.Infrastructure.Persistence;

#nullable disable

namespace VCare.Modules.CarePlans.Migrations
{
    [DbContext(typeof(CarePlanDbContext))]
    [Migration("20261004215304_initialCarePlanMigration")]
    partial class initialCarePlanMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("CarePlan")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VCare.Modules.CarePlans.Domain.Entities.CarePlan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CareHomeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("CreatedDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("ModifiedDate")
                        .HasColumnType("date");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CareHomeId");

                    b.HasIndex("PatientId");

                    b.ToTable("CarePlans", "CarePlan");
                });

            modelBuilder.Entity("VCare.Modules.CarePlans.Domain.Entities.CarePlan", b =>
                {
                    b.OwnsMany("VCare.Modules.CarePlans.Domain.Entities.Diagnosis", "Diagnoses", b1 =>
                        {
                            b1.Property<Guid>("CarePlanId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("CarePlanId", "Id");

                            b1.ToTable("CarePlanDiagnoses", "CarePlan");

                            b1.WithOwner()
                                .HasForeignKey("CarePlanId");
                        });

                    b.OwnsMany("VCare.Modules.CarePlans.Domain.Entities.Intervention", "Intervention", b1 =>
                        {
                            b1.Property<Guid>("CarePlanId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<bool>("Implementation")
                                .HasColumnType("bit");

                            b1.HasKey("CarePlanId", "Id");

                            b1.ToTable("CarePlanInterventions", "CarePlan");

                            b1.WithOwner()
                                .HasForeignKey("CarePlanId");
                        });

                    b.OwnsMany("VCare.Modules.CarePlans.Domain.Entities.PatientGoals", "Goals", b1 =>
                        {
                            b1.Property<Guid>("CarePlanId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("GoalDescription")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("CarePlanId", "Id");

                            b1.ToTable("CarePlanGoals", "CarePlan");

                            b1.WithOwner()
                                .HasForeignKey("CarePlanId");
                        });

                    b.Navigation("Diagnoses");

                    b.Navigation("Goals");

                    b.Navigation("Intervention");
                });
#pragma warning restore 612, 618
        }
    }
}
