// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VCare.Modules.Visitation.Infrastructure.Persistence;

#nullable disable

namespace VCare.Modules.Visitation.Migrations
{
    [DbContext(typeof(VisitationDbContext))]
    partial class VisitationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Visitation")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VCare.Modules.Visitation.Domain.Entities.Visit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("CareHomeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CheckedInAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CheckedOutAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("VisitationSummary")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CareHomeId");

                    b.HasIndex("PatientId");

                    b.ToTable("Visits", "Visitation");
                });

            modelBuilder.Entity("VCare.Modules.Visitation.Domain.Entities.Visit", b =>
                {
                    b.OwnsOne("Visitation.Domain.Entities.FeedingTask", "FeedingTask", b1 =>
                        {
                            b1.Property<Guid>("VisitId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("FeedingTaskNote")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<bool>("IsFeedingCompleted")
                                .HasColumnType("bit");

                            b1.HasKey("VisitId");

                            b1.ToTable("Visits", "Visitation");

                            b1.WithOwner()
                                .HasForeignKey("VisitId");
                        });

                    b.OwnsOne("Visitation.Domain.Entities.MedicationTask", "MedicationTask", b1 =>
                        {
                            b1.Property<Guid>("VisitId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("IsMedicationCompleted")
                                .HasColumnType("bit");

                            b1.Property<string>("MedicationTaskNote")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("VisitId");

                            b1.ToTable("Visits", "Visitation");

                            b1.WithOwner()
                                .HasForeignKey("VisitId");
                        });

                    b.OwnsOne("Visitation.Domain.Entities.PersonalcareTask", "PersonalcareTask", b1 =>
                        {
                            b1.Property<Guid>("VisitId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("CareTaskNote")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<bool>("IsCareCompleted")
                                .HasColumnType("bit");

                            b1.HasKey("VisitId");

                            b1.ToTable("Visits", "Visitation");

                            b1.WithOwner()
                                .HasForeignKey("VisitId");
                        });

                    b.Navigation("FeedingTask");

                    b.Navigation("MedicationTask");

                    b.Navigation("PersonalcareTask");
                });
#pragma warning restore 612, 618
        }
    }
}
