// <auto-generated />
using System;
using Medications.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Vcare.Modules.Medications.Migrations
{
    [DbContext(typeof(MedicationDbContext))]
    partial class MedicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Medication")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Medications.Domain.Entities.DoseSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("AnchorDate")
                        .HasColumnType("date");

                    b.Property<int>("DaysOfWeek")
                        .HasColumnType("int");

                    b.Property<string>("Dose")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<int>("FType")
                        .HasColumnType("int");

                    b.Property<int>("IntervalDays")
                        .HasColumnType("int");

                    b.Property<Guid>("MedicationOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.PrimitiveCollection<string>("Times")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MedicationOrderId");

                    b.ToTable("DoseSchedule", "Medication");
                });

            modelBuilder.Entity("Medications.Domain.Entities.MedicationAdministration", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AdministeredAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("AdministeredByStaffId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CareHomeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MedicationOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OutcomeCodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ScheduledFor")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CareHomeId");

                    b.HasIndex("MedicationOrderId");

                    b.ToTable("MedicationAdminstration", "Medication");
                });

            modelBuilder.Entity("Medications.Domain.Entities.MedicationOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CareHomeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Instructions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsControlledDrug")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrn")
                        .HasColumnType("bit");

                    b.Property<string>("Medication")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Prescriber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrnIndication")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrnMaxDose24h")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PrnMinIntervalMinutes")
                        .HasColumnType("int");

                    b.Property<int>("Route")
                        .HasColumnType("int");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CareHomeId");

                    b.ToTable("MedicationOrder", "Medication");
                });

            modelBuilder.Entity("Medications.Domain.Entities.OutcomeCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DisplayLetter")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OutcomeCode", "Medication");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f3c9d1e5-6078-4901-c345-d678e901f234"),
                            DisplayLetter = "R",
                            Name = "Refused"
                        },
                        new
                        {
                            Id = new Guid("e2b8c0d4-5f67-4890-b234-c567d890e123"),
                            DisplayLetter = "T",
                            Name = "Taken"
                        });
                });

            modelBuilder.Entity("Medications.Domain.Entities.DoseSchedule", b =>
                {
                    b.HasOne("Medications.Domain.Entities.MedicationOrder", null)
                        .WithMany("Schedule")
                        .HasForeignKey("MedicationOrderId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Medications.Domain.Entities.MedicationAdministration", b =>
                {
                    b.HasOne("Medications.Domain.Entities.MedicationOrder", null)
                        .WithMany("Administrations")
                        .HasForeignKey("MedicationOrderId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Medications.Domain.Entities.MedicationOrder", b =>
                {
                    b.Navigation("Administrations");

                    b.Navigation("Schedule");
                });
#pragma warning restore 612, 618
        }
    }
}
